### ISSUE TITLE
My gpu is TitanX, memory is 12G, but when I test the code in wider, it shows 'out of memory'????

### ISSUE THREAD

**Issue by hdjsjyl** [sfzhang15/SFD#17]
My gpu is TitanX, memory is 12G, but when I test the code in wider, it shows 'out of memory'???? Anyone meets the same problem?

**Comment by lwoiceshyn** [comment]
Yes, same problem for me.

**Comment by sfzhang15** [comment]
@hdjsjyl @lwoiceshyn 
Hi, I follow the instruction to test on WIDER FACE and the test is as follow:
![image](https://user-images.githubusercontent.com/31090111/36339315-64d775b2-13fd-11e8-9843-2c936f064a74.png)
The GPU memroy is only about 6G. We use titian x (Maswell) with cuda-8.0 and cudnn-6.0.

**Comment by lwoiceshyn** [comment]
Thanks for your response @sfzhang15.

I was using cudnn 7.0, and that was the cause for it not working. I switched to 6.0 and now it works @hdjsjyl .

**Comment by hdjsjyl** [comment]
@sfzhang15 , thank you very much. @lwoiceshyn thank you, I will try again.

**Comment by jesszgc** [comment]
@sfzhang15 I am using 8G memory without GPU in CPU mode, can CPU mode work OK on your PC?

**Comment by sfzhang15** [comment]
@jesszgc 
Sorry, we have not run it on the PC and only on the server. Besides, 8G memory may be too small.
